export enum TODO_ACTIONS {
  SET_LOADING = "SET_LOADING",
  FETCH_TODOS = "FETCH_TODOS",
  FETCH_TODOS_REQUESTED = "FETCH_TODOS_REQUESTED",
  TOGGLE_STATUS_TODO = "TOGGLE_STATUS_TODO",
  TOGGLE_STATUS_TODO_REQUESTED = "TOGGLE_STATUS_TODO_REQUESTED",
  DELETE_TODO = "DELETE_TODO",
  DELETE_TODO_REQUESTED = "DELETE_TODO_REQUESTED",
  CREATE_TODO = "CREATE_TODO",
  CREATE_TODO_REQUESTED = "CREATE_TODO_REQUESTED"
}
